name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      working-directory: app
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      working-directory: app
      run: npm install
    - name: Build page
      working-directory: app
      run: npm run build
    - name: Create cname file
      working-directory: app
      uses: finnp/create-file-action@master
      env:
        FILE_NAME: "./build/CNAME"
        FILE_DATA: "sequence.obis.org"
    - name: Deploy to gh-pages
      working-directory: app
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build